### ISSUE TITLE
Don't Check In Build Folder

### ISSUE THREAD

**Issue by David-Durst** [adamdai/magmacam#6]
You shouldn't check in generated things like the IceStick/build folder. It slows down git and makes cloning the repo more difficult. 
The aetherling/coreir_compile.sh (and other scripts) should be able to generate this.

**Comment by adamdai** [comment]
Okay, I remembered there is a Makefile I would like to keep in the build directory, so I ended up just ignoring all .blif, .bin, .v etc. files in the gitignore.
